name: zhwa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
   
  flutter_localizations:
    sdk: flutter
  

  #provide the first screen when app runs
  flutter_native_splash: ^2.4.6 
  #for responsive design
  flutter_screenutil: ^5.9.3
  #for icons
  iconsax: ^0.0.8
  #for 2 language and localization
  intl: ^0.20.2
  #for shared preferences
  shared_preferences: ^2.2.2
  #for state management
  flutter_bloc: ^8.1.3
  #for lottie animations
  lottie: ^3.3.1
  #for HTTP requests
  http: ^1.1.0
  dio: ^5.4.0
  #for JSON serialization
  json_annotation: ^4.8.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  #for app icons
  flutter_launcher_icons: ^0.14.4
  #for JSON code generation
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/translations/

  fonts:
    - family: "IBMPlexSansArabic"
      fonts:
        - asset: "assets/fonts/IBMPlexSansArabic-Regular.ttf"
        - asset: "assets/fonts/IBMPlexSansArabic-Thin.ttf"
        - asset: "assets/fonts/IBMPlexSansArabic-Light.ttf"
        - asset: "assets/fonts/IBMPlexSansArabic-Bold.ttf"




flutter_native_splash:
  android: true
  ios: true
  web: false
  fullscreen: true
  background_image: assets/images/splash_screen.png
  
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png"